# config/packages/messenger.yaml
framework:
    messenger:
        transports:
            amqp_email_notification:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                options:
                    exchange:
                        name: email_notifications
                        type: fanout
                    queues:
                        email_notifications: ~
        routing:
            App\Message\EmailNotification: amqp_email_notification
