name: 'Production Build'

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v1
      - uses: ./.github/actions/deploy
        env:
          VAULT_PASS: ${{ secrets.VAULT_PASS }}
